classDiagram
class Album {
	AlbumId: INTEGER
	Titolo: TEXT
	ArtistaId: INTEGER
}

class Artista {
	ArtistaId: INTEGER
	Nome: TEXT
}

class Cliente {
	ClienteId: INTEGER
	Nome: TEXT
	Cognome: TEXT
	Societa: TEXT
	Indirizzo: TEXT
	Citta: TEXT
	Stato: TEXT
	Nazione: TEXT
	CodicePostale: TEXT
	Telefono: TEXT
	Fax: TEXT
	Email: TEXT
	AssistenteId: INTEGER
}

class Dipendente {
	DipendenteId: INTEGER
	Cognome: TEXT
	Nome: TEXT
	Titolo: TEXT
	SuperioreId: INTEGER
	DataNascita: DATETIME
	DataAssunzione: DATETIME
	Indirizzo: TEXT
	Citta: TEXT
	Stato: TEXT
	Nazione: TEXT
	CodicePostale: TEXT
	Telefono: TEXT
	Fax: TEXT
	Email: TEXT
}

class Genere {
	GenereId: INTEGER
	Nome: TEXT
}

class Fattura {
	FatturaId: INTEGER
	ClienteId: INTEGER
	DataFatturazione: DATETIME
	IndirizzoFatturazione: TEXT
	CittaFatturazione: TEXT
	StatoFatturazione: TEXT
	NazioneFatturazione: TEXT
	CodicePostaleFatturazione: TEXT
	Totale: REAL(10,2)
}

class LineaFattura {
	LineaFatturaId: INTEGER
	FatturaId: INTEGER
	TracciaId: INTEGER
	PrezzoUnitario: REAL(10,2)
	Quantita: INTEGER
}

class FormatoMultimediale {
	FormatoMultimedialeId: INTEGER
	Nome: TEXT
}

class Playlist {
	PlaylistId: INTEGER
	Nome: TEXT
}

class TracciaPlaylist {
	PlaylistId: INTEGER
	TracciaId: INTEGER
}

class Traccia {
	TracciaId: INTEGER
	Nome: TEXT
	AlbumId: INTEGER
	FormatoMultimedialeId: INTEGER
	GenereId: INTEGER
	Compositori: TEXT
	Millisecondi: INTEGER
	Byte: INTEGER
	PrezzoUnitario: REAL(10,2)
}

Album "*" -- "1" Artista : ArtistaId
Cliente "*" -- "1" Dipendente : AssistenteId
Dipendente "*" -- "1" Dipendente : SuperioreId
Fattura "*" -- "1" Cliente : ClienteId
LineaFattura "*" -- "1" Traccia : TracciaId
LineaFattura "*" -- "1" Fattura : FatturaId
TracciaPlaylist "*" -- "1" Traccia : TracciaId
TracciaPlaylist "*" -- "1" Playlist : PlaylistId
Traccia "*" -- "1" FormatoMultimediale : FormatoMultimedialeId
Traccia "*" -- "1" Genere : GenereId
Traccia "*" -- "1" Album : AlbumId

